#!/usr/bin/env bash
# Infinite loop that catches the SIGTERM signal and claims invincibility
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
